### ISSUE TITLE
Calling AutoFitColumns gives Error on Linux but works fine on Windows.

### ISSUE THREAD

**Issue by paulvanbladel** [VahidN/EPPlus.Core#41]
Thanks for this great library on .net core.

# Summary of the issue
Calling AutoFitColumns gives Error on Linux but works fine on Windows.

Z System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found.

## Environment
Ubuntu 16.4 and windows 10
```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2015)
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
  Connection id "0HLADVPESJ1IA", Request id "0HLADVPESJ1IA:00000004": An unhandled exception was thrown by the application.
2017-12-28T14:22:23.447145539Z System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found.
2017-12-28T14:22:23.447148953Z  (Exception from HRESULT: 0x8007007E)
2017-12-28T14:22:23.447151528Z    at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
2017-12-28T14:22:23.447154433Z    at System.Drawing.GDIPlus..cctor()
2017-12-28T14:22:23.447156948Z    --- End of inner exception stack trace ---
2017-12-28T14:22:23.447159412Z    at System.Drawing.GDIPlus.GdipGetGenericFontFamilySansSerif(IntPtr& fontFamily)
2017-12-28T14:22:23.447162155Z    at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
2017-12-28T14:22:23.447164711Z    at System.Drawing.FontFamily.get_GenericSansSerif()
2017-12-28T14:22:23.447167249Z    at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
2017-12-28T14:22:23.447169981Z    at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)

```

**Comment by paulvanbladel** [comment]
In the very latest version (1.5.4)
The error message is slightly different:
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libdl': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Libdl.dlopen(String fileName, Int32 flag)
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)

**Comment by VahidN** [comment]
- v1.5.4 uses Microsoft's `System.Drawing.Common` library. It's in the preview phase right now. To fix `Unable to load DLL 'libdl'` error, you should 
```
 symlink /lib64/libdl.so.2 to /lib64/libdl.so
```
[More info](https://github.com/dotnet/corefx/issues/25102)
- Or you can install v1.5.2 which uses `CoreCompat.System.Drawing.v2`
```
 Install-Package EPPlus.Core -Version 1.5.2
```
Also you need to install `libgdiplus` too.
```
For Ubuntu 16.04 and above:
    apt-get install libgdiplus
    cd /usr/lib
    ln -s libgdiplus.so gdiplus.dll
```

**Comment by paulvanbladel** [comment]
@VahidN  Thanks a lot. Closing the question. Cheers.
