### ISSUE TITLE
[Exception] Reading file on linux

### ISSUE THREAD

**Issue by tartexs** [VahidN/EPPlus.Core#6]
Runing a new project to read a simple file on linux:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ole32.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at OfficeOpenXml.Utils.CompoundDocument.StgIsStorageFile(String pwcsName)
   at OfficeOpenXml.ExcelPackage.ConstructNewFile(String password)

**Comment by tartexs** [comment]
Sorry, i was trying to open an xls file.
